### PR TITLE
feat: add oci talos cluster

### PR DESCRIPTION
**Pull request by BobyMCbobs**
adds terraform to configure a talos cluster on oci

### CODE REVIEW

**Comment by BobyMCbobs** [comment]
upload an image with

https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/core_image

**Comment by hh** [comment]
I wonder if we can use talos factory api to create the image and upload it

**Comment by hh** [comment]
I think here is our latest code for talos factory image creation: https://github.com/sharingio/infra/blob/main/terraform/equinix-metal-talos-cluster/talos.tf#L20-L41

**Comment by BobyMCbobs** [comment]
> I wonder if we can use talos factory api to create the image and upload it
> I think here is our latest code for talos factory image creation: https://github.com/sharingio/infra/blob/main/terraform/equinix-metal-talos-cluster/talos.tf#L20-L41

Yes, _should_ be possible with
https://registry.terraform.io/providers/oracle/oci/latest/docs/resources/core_image

**Comment by BobyMCbobs** [comment]
CSI would be another helpful type of component to have
https://oracle.github.io/cluster-api-provider-oci/gs/install-csi.html

**Comment by BobyMCbobs** [comment]
Almost completed adding
https://oracle.github.io/cluster-api-provider-oci/gs/install-oci-ccm.html

**Comment by BobyMCbobs** [comment]
replaced by https://github.com/sharingio/infra/pull/2

**Pull request closed without merging**
